### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by xiangzhu** [statgen/emeraLD#4]
Thanks for developing and sharing this wonderful tool! I was trying to install the software but unfortunately got different errors in both macOS and Linux environment. Below are the error messages. I wonder if you could help identify the problems at your convenience.

### error in macOS

```zsh
# xiangzhu @ stanford in ~/GitHub/emeraLD on git:master o [15:58:14] C:2
$ make
c++ -std=c++11 -Ofast -flto -pipe  -c -o src/Main.o src/Main.cpp
In file included from src/Main.cpp:1:
In file included from src/processGenotypes.hpp:13:
src/boost/dynamic_bitset.hpp:15:10: fatal error: 'boost/dynamic_bitset/dynamic_bitset.hpp' file not
      found
#include "boost/dynamic_bitset/dynamic_bitset.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/Main.o] Error 1
```

Here is the info about this MacOS environment:

```zsh
$ uname -a
Darwin stanford 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

### error in Linux

```zsh
# xiangzhu @ midway-login1 in ~/emeraLD on git:master o [18:03:41]
$ make
g++ -std=c++11 -Ofast -flto -pipe  -c -o src/calcLD.o src/calcLD.cpp
cc1plus: error: invalid option argument ‘-Ofast’
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-flto"
make: *** [src/calcLD.o] Error 1
```

Here is the info about this Linux environment:

```zsh
$ cat /proc/version
Linux version 2.6.32-696.23.1.el6.x86_64 (mockbuild@sl6.fnal.gov) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Tue Mar 13 17:46:31 CDT 2018
```

**Comment by welchr** [comment]
Try the following for MacOS: 

```
git clone git@github.com:statgen/emeraLD.git
cd emeraLD
git checkout fix/macos-compile
make
```

Does that work?

**Comment by corbinq** [comment]
Hi,

Thanks for contacting us about this.  For the Linux error, I'd recommend
either 1) replacing "-Ofast -flto" with "-O3" in the makefile, or 2)
updating gcc. I'll try to patch this in next update

Best,
Corbin

**Comment by xiangzhu** [comment]
@welchr  Thank you for the help with MacOS; it seems that it is working now.

```zsh
$ make
c++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/Main.o src/Main.cpp
c++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/calcLD.o src/calcLD.cpp
c++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/processGenotypes.o src/processGenotypes.cpp
c++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/tabix_util/tabix.o src/tabix_util/tabix.cpp
cc  -Ofast -flto -pipe -Isrc  -c -o src/tabix_util/index.o src/tabix_util/index.c
cc  -Ofast -flto -pipe -Isrc  -c -o src/tabix_util/bgzf.o src/tabix_util/bgzf.c
src/tabix_util/bgzf.c:275:17: warning: implicit conversion from 'const int' to 'bgzf_byte_t'
      (aka 'signed char') changes value from 139 to -117 [-Wconstant-conversion]
    buffer[1] = GZIP_ID2;
              ~ ^~~~~~~~
src/tabix_util/bgzf.c:283:17: warning: implicit conversion from 'const int' to 'bgzf_byte_t'
      (aka 'signed char') changes value from 255 to -1 [-Wconstant-conversion]
    buffer[9] = OS_UNKNOWN;
              ~ ^~~~~~~~~~
2 warnings generated.
c++ -Ofast -flto -pipe -Isrc -o bin/emeraLD src/Main.o src/calcLD.o src/processGenotypes.o src/tabix_util/tabix.o src/tabix_util/index.o src/tabix_util/bgzf.o -lz -lm
```

```R
> source('emeraLD2R.r');
Loading required package: data.table
data.table 1.11.4  Latest news: http://r-datatable.com
emeraLD v0.1 (c) 2018 corbin quick (corbinq@gmail.com)

reading from m3vcf file...

processed genotype data for 5008 haplotypes...

calculating LD for 60 SNPs...

done!! thanks for using emeraLD
```

**Comment by welchr** [comment]
Roger that. 

@corbinq - on MacOS, there seemed to be two problems I ran into: 

1. The Makefile needs `-Isrc` specifically, but it doesn't seem to be necessary on linux (?)
2. There were some missing boost header files. On our gateway machines, they look to be already installed in `/usr/include/boost`, and are included in the default search path for gcc/g++. So that might be why compile succeeds there, but fails on other machines that don't already have boost. 

The `fix/macos-compile` branch fixes the Makefile and adds in the missing headers, but I haven't tested it back on linux, which would probably be a good idea before merging.

**Comment by xiangzhu** [comment]
@corbinq  Thanks for the help! I replaced "-Ofast -flto" with "-O3", but I still got the following error.

```zsh
diff --git a/Makefile b/Makefile
index f4b429f..e93ef00 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 VERSION=0.1

-CPPFLAGS= -Ofast -flto -pipe
+CPPFLAGS= -O3 -pipe
 CXXFLAGS= -std=c++11

 LDFLAGS= -lz -lm
```

```zsh
$ make
g++ -std=c++11 -O3 -pipe  -c -o src/calcLD.o src/calcLD.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [src/calcLD.o] Error 1
```

Regarding the version of `gcc`, which one do you recommend? Below is the default one installed in my Linux server.

```zsh
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by welchr** [comment]
Looks like you need at least GCC 4.8.1 for `-std=c++11`. 

https://gcc.gnu.org/projects/cxx-status.html#cxx11

**Comment by xiangzhu** [comment]
@welchr  thanks now it also works in my Linux environment! Please feel free to close this issue.

```zsh
$ module load gcc/4.8
$ make
cc  -O3 -pipe  -c -o src/tabix_util/index.o src/tabix_util/index.c
cc  -O3 -pipe  -c -o src/tabix_util/bgzf.o src/tabix_util/bgzf.c
g++ -O3 -pipe -o bin/emeraLD src/calcLD.o src/Main.o src/processGenotypes.o src/tabix_util/tabix.o src/tabix_util/index.o src/tabix_util/bgzf.o -lz -lm
```

```r
> source('emeraLD2R.r')
Loading required package: data.table
data.table 1.10.4
  The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
  Documentation: ?data.table, example(data.table) and browseVignettes("data.table")
  Release notes, videos and slides: http://r-datatable.com
emeraLD v0.1 (c) 2018 corbin quick (corbinq@gmail.com)

reading from m3vcf file...

processed genotype data for 5008 haplotypes...

calculating LD for 60 SNPs...

done!! thanks for using emeraLD
```

**Comment by eacton** [comment]
Hello @welchr  @corbinq!  I also am getting a make error on Linux. I performed the substitution of  "-Ofast -flto" with "-O3" in the makefile, and I am using gcc v 7.3.0. 

     g++ -std=c++11 -O3 -pipe  -c -o src/processGenotypes.o src/processGenotypes.cpp
     In file included from src/processGenotypes.hpp:13:0,
                 from src/processGenotypes.cpp:1:
     src/boost/dynamic_bitset.hpp:15:10: fatal error: boost/dynamic_bitset/dynamic_bitset.hpp: No such file or directory
      #include "boost/dynamic_bitset/dynamic_bitset.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     compilation terminated. 
     <builtin>: recipe for target 'src/processGenotypes.o' failed


The boost/dynamic_bitset/dynamic_bitset.hpp file clearly exists...
Any ideas?


System info: Linux version 4.15.0-45-generic (buildd@lgw01-amd64-031) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3))

**Comment by welchr** [comment]
@eacton Can you try compiling from this branch and see if that does the trick? That particular compile issue may have been fixed already and not merged in yet, but I can't recall.

```bash
git clone git@github.com:statgen/emeraLD.git
cd emeraLD
git checkout fix/macos-compile
make
```

**Comment by eacton** [comment]
Thanks @welchr for the quick response. I got one warning (see below), but otherwise it looks okay. So this means I don't have to do the -O3 substitution, then? Or do you think its related to the error?

     g++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/processGenotypes.o src/processGenotypes.cpp
     g++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/Main.o src/Main.cpp
     g++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/calcLD.o src/calcLD.cpp
     g++ -std=c++11 -Ofast -flto -pipe -Isrc  -c -o src/tabix_util/tabix.o src/tabix_util/tabix.cpp
     gcc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2  -pipe -fPIC -Ofast -flto -pipe -Isrc  -c -o src/tabix_util/index.o src/tabix_util/index.c
     gcc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -Ofast -flto -pipe -Isrc  -c -o src/tabix_util/bgzf.o src/tabix_util/bgzf.c
     src/tabix_util/bgzf.c: In function ‘bgzf_check_EOF’:
     src/tabix_util/bgzf.c:681:2: warning: ignoring return value of ‘fread’, declared with attribute        warn_unused_result [-Wunused-result]
    fread(buf, 1, 28, fp->file);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    g++ -Ofast -flto -pipe -Isrc -o bin/emeraLD src/processGenotypes.o src/Main.o src/calcLD.o src/tabix_util/tabix.o src/tabix_util/index.o src/tabix_util/bgzf.o -lz -lm
